// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ModelBuilder
{
    public partial class ModelBuilder
    {
        /// <summary>
        /// model input class for ModelBuilder.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"species")]
            public string Species { get; set; }

            [ColumnName(@"island")]
            public string Island { get; set; }

            [ColumnName(@"culmen_length_mm")]
            public float Culmen_length_mm { get; set; }

            [ColumnName(@"culmen_depth_mm")]
            public float Culmen_depth_mm { get; set; }

            [ColumnName(@"flipper_length_mm")]
            public float Flipper_length_mm { get; set; }

            [ColumnName(@"body_mass_g")]
            public float Body_mass_g { get; set; }

            [ColumnName(@"sex")]
            public string Sex { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ModelBuilder.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion


        private static readonly string _fileName = "ModelBuilder.zip";
        private static readonly string _mlNetModelPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory.Split(@"\bin")[0], _fileName);

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(_mlNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
